title: I want to use different keys
hero_image: images/banner.png
description: I want to use different keys
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: I want to use different keys
